Book detail
wolox-training/ng-angular pull request #3
Opened 2020-02-07 00:59 UTC by GNico95

**Summary**

The bookDetail.html file in which the details were written was added and the image of a book with the corresponding styles was placed, according to the card Detail of book 1, Detail of book 2 and Detail of book 3.

**Trello Card**

- https://trello.com/c/GH7EgnOH/26-detalle-de-libro-i-textos

- https://trello.com/c/K4G6aUHp/27-detalle-de-libro-ii-imagen

- https://trello.com/c/KvB6oCNE/28-detalle-de-libro-iii-estructura

2020-02-07 14:39 UTC, martinmona commented
Remember to use the PR template 
````
## Summary
- Completed the project setup
- Finished PR structure

## Screenshot
Imagen o gif

## Trello Card
https://trello.com/c/eDUCaVcx/38-pull-request

````

2020-02-07 16:24 UTC, idcuadrowolox requested changes

2020-02-07 16:24 UTC, idcuadrowolox commented on bookDetail.html
> +
Remove empty line

2020-02-07 16:24 UTC, idcuadrowolox commented on bookDetail.html
> +
Remove empty line

2020-02-07 16:24 UTC, idcuadrowolox commented on bookDetail.html
> +
Remove empty line

2020-02-07 16:24 UTC, idcuadrowolox commented on bookDetail.html
> +
Remove empty line

2020-02-07 16:24 UTC, idcuadrowolox commented on bookDetail.html
> +	<meta name="viewport" content="width=device-width, initial-scale=1.0">
fix indentation

2020-02-07 16:24 UTC, idcuadrowolox commented on bookDetail.html
> +                    <div class="underline"></div>
Add the underline to h1 tag

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/detail.scss
> +    background-color: #BED23C;
use scss variables for colors

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/detail.scss
> +@import 'colors';
use 2 spaces for indent

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/detail.scss
> +* {
I think you can put this in application.scss

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/detail.scss
> +    margin: 3%;
put padding in parent container

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/detail.scss
> +    @extend %conteiner-book-elements-height;
unnecessary property, when you work with images is a good practice to set only with o height.

2020-02-07 16:24 UTC, idcuadrowolox commented on bookDetail.html
> +                <section class="section-book">
Remove container

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/detail.scss
> +    justify-content: flex-start;
please, order alphabetically

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/colors.scss
> +$detail-book-color: #000;
I think it's better to use variables like $black, $main-green for example

2020-02-07 16:24 UTC, idcuadrowolox commented on scss/detail.scss
> +    width: 75%;
work responsive views with media queries

2020-02-07 16:47 UTC, idcuadrowolox requested changes

2020-02-07 16:47 UTC, idcuadrowolox commented on bookDetail.html
> +            <img class="book-cover" src="images/book-cover.png" />
It's a good practice to add the alt attribute to image tags

2020-02-07 18:21 UTC, martinmona requested changes

2020-02-07 18:21 UTC, martinmona commented on bookDetail.html
> +
delete empty spaces

2020-02-07 18:21 UTC, martinmona commented on bookDetail.html
> +
same

2020-02-07 18:21 UTC, martinmona commented on bookDetail.html
> +    <div class="general-container">
Indentation is 2 spaces

2020-02-07 18:21 UTC, martinmona commented on bookDetail.html
> +                    <div class="underline"></div>
avoid using unnecessary tags, you can use `border-bottom`

2020-02-07 18:21 UTC, martinmona commented on scss/detail.scss
> +    display: flex;
remember 2 spaces indentation

2020-02-07 18:21 UTC, martinmona commented on scss/detail.scss
> +    line-height: 24px;
maybe you can use @mixin to change font-size, weight and line height

2020-02-07 18:21 UTC, martinmona commented on scss/colors.scss
> +$general-background-color: #F4F4F4;
> this color variables should describe how the color looks and not where it is used


Check the tech-guides, and [Name that color](http://chir.ag/projects/name-that-color/) page

2020-02-10 17:37 UTC, idcuadrowolox requested changes

2020-02-10 17:37 UTC, idcuadrowolox commented on scss/detail.scss
>  .detail {
Please check indent in this class

2020-02-10 17:37 UTC, idcuadrowolox commented on scss/detail.scss
> +	font-weight: $weight;
please check indent

2020-02-10 17:37 UTC, idcuadrowolox commented on scss/detail.scss
>  .description {
please check indent in this class

2020-02-10 17:37 UTC, idcuadrowolox commented on scss/detail.scss
>  	font-weight: 700;
check Indent

2020-02-10 17:37 UTC, idcuadrowolox commented on scss/detail.scss
>  	height: 100vh;
please check indent

2020-02-10 17:37 UTC, idcuadrowolox commented on scss/detail.scss
>  	justify-content: center;
please check indent

2020-02-10 17:37 UTC, idcuadrowolox commented on scss/colors.scss
> +$green: #BED23C;
Order alphabetically

2020-02-10 19:00 UTC, idcuadrowolox approved these changes

2020-02-10 19:10 UTC, nvescio requested changes

2020-02-10 19:10 UTC, nvescio commented on scss/detail.scss
> +  height: 368px;
Check here, you've `height` twice

2020-02-10 19:12 UTC, nvescio approved these changes

2020-02-10 22:11 UTC, martinmona approved these changes

2020-02-11 18:03 UTC, martinmona approved these changes

2020-02-11 18:03 UTC, martinmona commented on scss/detail.scss
> +  justify-content: center;
Not necessary to use flex here, if you want to center the `container-book` class you can use `margin: 0 auto` there

2020-02-11 18:03 UTC, martinmona commented on scss/detail.scss
> +  flex-flow: column nowrap;
```suggestion
  flex-direction: column;
```

2020-02-11 18:03 UTC, martinmona commented on scss/detail.scss
> +  width: 500px;
add `max-width: 100%`

2020-02-11 18:03 UTC, martinmona commented on scss/detail.scss
> +  width: 98px;
maybe it's not necessary

2020-02-11 18:03 UTC, martinmona commented on bookDetail.html
> +      <img class="book-cover" src="images/book-cover.png" alt="book-cover"/>
Create an `assets` folder and move this image there

2020-02-11 18:03 UTC, martinmona commented on scss/detail.scss
> +  height: 30px;
you are already using `line-height` instead

2020-02-13 14:55 UTC, martinmona approved these changes

2020-02-14 14:55 UTC, merged