Book detail 4
wolox-training/ng-angular pull request #4
Opened 2020-02-10 19:02 UTC by GNico95

**Summary**
Add book badge in book detail

** Screenshot**

<img width="1680" alt="Captura de Pantalla 2020-02-10 a la(s) 16 02 13" src="https://user-images.githubusercontent.com/43755614/74180685-b7868e00-4c1e-11ea-840f-0f4ba3e0660c.png">

**Trello Card**

https://github.com/wolox-training/ng-angular/compare/book-detail...book-detail-4?expand=1

2020-02-10 20:11 UTC, idcuadrowolox requested changes

2020-02-10 20:11 UTC, idcuadrowolox commented on scss/detail.scss
> +  background-size: 100% 100%;
I think It's better to set width or height in images, not both

2020-02-10 20:11 UTC, idcuadrowolox commented on scss/detail.scss
> +.book-badge {
I think it's better put this image as :before selector in image container

2020-02-10 22:11 UTC, idcuadrowolox approved these changes

2020-02-10 22:22 UTC, martinmona requested changes

2020-02-10 22:22 UTC, martinmona commented on bookDetail.html
> +        <div class="book-images">
I think you can do it without this tag

2020-02-10 22:22 UTC, martinmona commented on scss/detail.scss
>    width: 900px;
Please, add `max-width: 100%;`

2020-02-10 22:22 UTC, martinmona commented on scss/detail.scss
>    max-height: 100%;
Delete this

2020-02-11 17:43 UTC, martinmona requested changes

2020-02-11 17:43 UTC, martinmona commented on scss/detail.scss
> +    background: url(../images/badge.png) no-repeat;
The correct way is using `background-image` property

2020-02-11 17:43 UTC, martinmona commented on scss/detail.scss
>    justify-content: flex-start;
That's the value by default, so delete this.

2020-02-11 17:43 UTC, martinmona commented on scss/detail.scss
>    flex-flow: column nowrap;
```suggestion
  flex-direction: column;
```

2020-02-13 15:10 UTC, martinmona approved these changes

2020-02-13 15:14 UTC, nvescio approved these changes

2020-02-14 14:54 UTC, merged