Book List and Nav Bar
wolox-training/ng-angular pull request #5
Opened 2020-02-16 20:07 UTC by GNico95

**Summary**

Create Book list and nav bar in Index.html

**Screenshot**

<img width="1680" alt="Captura de Pantalla 2020-02-16 a la(s) 17 06 16" src="https://user-images.githubusercontent.com/43755614/74611867-b3ef7d00-50de-11ea-8ad6-e9e5c8f834e7.png">

**Trello Card**

https://trello.com/c/4Ko58GJH/30-listado-de-libros

https://trello.com/c/zLhM6Waq/31-navbar

2020-02-18 14:11 UTC, martinmona requested changes

2020-02-18 14:11 UTC, martinmona commented on index.html
> +    <a class="wolox-image" href="#" target="_self"> </a>
I think it'd be better like an `img` tag, and then, if you need it to behave as a link then wrap it inside an` a` tag

2020-02-18 14:11 UTC, martinmona commented on scss/book-list.scss
> +  overflow-y: scroll;
don't use it here

2020-02-18 14:11 UTC, martinmona commented on scss/book-list.scss
> +  height: 18px;
not necessary

2020-02-18 14:11 UTC, martinmona commented on scss/book-list.scss
> +  width: 63px;
not necessary

2020-02-18 14:11 UTC, martinmona commented on scss/book-list.scss
> +  max-width: 100%;
```suggestion
  width: 100%;
```

2020-02-18 16:42 UTC, martinmona approved these changes
:clap:

2020-02-18 19:24 UTC, nvescio requested changes

2020-02-18 19:24 UTC, nvescio commented on scss/book-list.scss
> +  background-color: white;
Use variable here

2020-03-09 14:54 UTC, nvescio approved these changes

2020-03-09 20:31 UTC, merged