Login
wolox-training/ng-angular pull request #7
Opened 2020-02-18 19:12 UTC by GNico95

**Summary**

Add login.html into the project 

**Screenshoot**

![Captura de Pantalla 2020-02-18 a la(s) 16 02 28](https://user-images.githubusercontent.com/43755614/74769493-458af600-5269-11ea-82ab-c973a54fe05c.png)

**Trello Card**

https://trello.com/c/xaSggaPg/32-login

2020-02-26 15:13 UTC, martinmona requested changes

2020-02-26 15:13 UTC, martinmona commented on scss/login.scss
> +	@extend %display-config-vertical;
Check the identation

2020-02-26 15:13 UTC, martinmona commented on scss/login.scss
> +	max-width: 100%;
not necessary

2020-02-26 15:13 UTC, martinmona commented on scss/login.scss
> +  color: white;
use a variable

2020-02-26 15:13 UTC, martinmona commented on scss/login.scss
> +	background: $dark-grey;
```suggestion
	background-color: $dark-grey;
```

2020-03-10 15:55 UTC, martinmona approved these changes
chec identation in login.scss

2020-03-13 13:02 UTC, nvescio requested changes

2020-03-13 13:02 UTC, nvescio commented on scss/login.scss
> +}
Check indentation 😬

2020-03-13 14:43 UTC, nvescio approved these changes

2020-09-09 23:01 UTC, merged