add media query in bookDetail.html
wolox-training/ng-angular pull request #8
Opened 2020-03-09 20:41 UTC by GNico95

**Summary**
Add media query in bookDetail.html

**Screenshot**

<img width="696" alt="Captura de Pantalla 2020-03-09 a la(s) 17 30 48" src="https://user-images.githubusercontent.com/43755614/76255381-d7649e00-622c-11ea-92fa-43324cd5e46e.png">

**Trello**

https://trello.com/c/T5wgUHlZ/34-responsive

2020-03-10 16:02 UTC, martinmona requested changes

2020-03-10 16:02 UTC, martinmona commented on scss/detail.scss
> +    display: flex;
:thinking:

2020-03-10 16:02 UTC, martinmona commented on scss/detail.scss
> +    height: 39px;
don't set height for text, you have line-height already

2020-03-10 16:02 UTC, martinmona commented on scss/detail.scss
> +    height: 16px;
same

2020-03-10 16:02 UTC, martinmona commented on scss/detail.scss
> +    height: 22px;
same

2020-03-10 16:02 UTC, martinmona commented on scss/detail.scss
> +    height: 22px;
![image](https://user-images.githubusercontent.com/11933480/76332406-1814f380-62cf-11ea-825c-aedb6b8d7816.png)

2020-03-10 19:59 UTC, martinmona approved these changes

2020-03-13 13:03 UTC, nvescio approved these changes

2020-09-09 23:00 UTC, merged